# Prometheus config to scrape a host-running RLTrainer metrics endpoint (localhost:9090)
global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'mage-host'
    static_configs:
      - targets: ['host.docker.internal:9090']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

